# Generated by Django 6.0.5 on 2026-06-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidadecurricular',
            old_name='objectivos',
            new_name='objectivo',
        ),
    ]
