# Generated by Django 6.0.5 on 2026-06-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_objectivos_unidadecurricular_objectivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadecurricular',
            options={'verbose_name': 'Unidade curricular', 'verbose_name_plural': 'Unidades curriculares'},
        ),
    ]
