# Generated by Django 6.0.5 on 2026-05-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('mestre', models.CharField(max_length=100)),
                ('mundo', models.CharField(max_length=100)),
                ('nivel_recomendado', models.IntegerField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicaAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('duracao', models.IntegerField()),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='dnd.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('vida', models.IntegerField()),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to='dnd.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('recompensa_ouro', models.IntegerField()),
                ('concluida', models.BooleanField(default=False)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes', to='dnd.campanha')),
                ('personagens', models.ManyToManyField(related_name='missoes', to='dnd.personagem')),
            ],
        ),
    ]
