# Generated by Django 6.0.5 on 2026-05-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicaambiente',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
