# Generated by Django 6.0.5 on 2026-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_musicaambiente_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicaambiente',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
