# Generated by Django 6.0.5 on 2026-06-03 14:00

import dnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_alter_musicaambiente_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome de quem vai usar a chave', max_length=100)),
                ('key', models.CharField(default=dnd.models.generate_api_key, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
